-- Create the db hbtn_0d_usa
-- containing table states(id INT UNIQUE NOT NULL AUTO_INCREMENT PRIMARY KEY, name VARCHAR(256) NOT NULL)
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
CREATE TABLE
	IF NOT EXISTS hbtn_0d_usa.states (
		id INT UNIQUE NOT NULL AUTO_INCREMENT PRIMARY KEY,
		name VARCHAR(256) NOT NULL
	)
